### ISSUE TITLE
StructureSets: Allow for complex, reusable mappings

### ISSUE THREAD

**Issue by dbarr99** [sdmx-twg/sdmx-im#10]
Allow for many to one and many to many mappings.

Enable code list maps that can be cross-referenced between different dataset mappings.

More details attached.

[SDMX_StructureSet_limitations.docx](https://github.com/sdmx-twg/sdmx-ml-v2_1/files/106179/SDMX_StructureSet_limitations.docx)

**Comment by stratosn** [comment]
As of SDMX 3.0, all of maps of a 2.1 `StructureSet` have become _MantainableArtefacts_ and may be reused by reference.
SDMX 3.0 includes the following mapping Artefacts:
- StructureMap
- RepresentationMap
- ConceptSchemeMap
- CategorySchemeMap
- ReportingTaxonomyMap
- OrganisationSchemeMap
