### ISSUE TITLE
Allow referencing of Hierarchical Code Lists

### ISSUE THREAD

**Issue by dbarr99** [sdmx-twg/sdmx-im#11]
To consider renaming the HCL artefact to something more fitting, because it's not a code list.

Be clear on difference between HCL and StructureSet.

An HCL can useful to define code sets that are used for data dissemination

It would be useful to be able to attach these to a Dataflow so that we can define hierarchies and additional visualisation codes that are not in the Codelist

Also to enable standard codelists to be used but with extensions (codes from other codelists)
This will facilitate the use of common codelists

**Comment by stratosn** [comment]
Hierarchies combined with HierarchyAssociations have been introduced in SDMX 3.0 to fulfil this requirement. 
@sdmx-twg/sdmx-im-team if you agree, we could close this issue.

**Comment by stratosn** [comment]
In SDMX 3.0, the `HierarchyAssociation` relates a Component (Dimension, Attribute, Measure) to a given Hierarchy in a given context (Dataflow, DataStructure, DataProvision).
For example, you can associate a `Hierarchy` of areas for a `Dimension` called "AREA" in the context of one of the `Dataflows` using that `Dimension`.
