### ISSUE TITLE
Simplify DSD Dimensions

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/sdmx-im#12]
Following the deprecation of the `MeasureDimension` in the context of issue #6, the idea to simplify the DSD by using only simple Dimensions with roles, has been put on the table.
In the case of the `MeasureDimension` the role `MEASURE` is proposed and similarly, in the case of the `TimeDimension` the role `TIME` could be used.

Doing that, and considering also #6, the Components of a DSD may be either of the following:
* Dimension
* Attribute
* Measure

The impact of this decision would be:
* In the DSD: there will be one way of defining a Dimension.
* In the dataset formats: there will not be any time-series specific dataset format.

**Comment by dosse** [comment]
Released as part of SDMX 3.0.0

**Comment by dosse** [comment]
Could someone please close this ticket?

**Comment by stratosn** [comment]
The simplification was implemented in SDMX 3.0, with the exception of the TimeDimension, which is still a special sub-class of Dimension.
