### ISSUE TITLE
Harmonize header specifications across data type

### ISSUE THREAD

**Issue by Tzaphkiel** [sdmx-twg/sdmx-im#17]
> _Received from IMF_

The header carries basic information about the SDMX file such as when it was created and the source.

Despite serving the same function in all SDMX file types there are **8 different header types** leading to needless complications in building and reading SDMX files. 

We recommend reducing the number of header types.

**Comment by stratosn** [comment]
The HeaderTypes have been reduced to 4, following the reduction of available XML message formats in SDMX 3.0.
We could considered this issue as closed, @agent96 ?

**Comment by tmartine** [comment]
I am sorry for not understanding the time difference…. It was your 9am or
mine. Best

Martine Tchitchihe
612 402 1978
*''L’école est une clef pour la vie" Baba Simon*
*"Teachers plant seeds of knowledge that last a lifetime"*
