### ISSUE TITLE
Code List extension/composition

### ISSUE THREAD

**Issue by dbarr99** [sdmx-twg/sdmx-im#2]
The main use case is the ability to extend a Cross-Domain Code List (CDCL) with extra codes. The ability to override CDCL codes should also be considered (though it may be considered an invalid practice).

For information: 
It is possible to do code list inheritance in HCLs but it can’t be used for data exchange in SDMX 2.1 as a DSD cannot reference an HCL, therefore;

- A new version of the standard is required for code list inheritance
- If we were designing SDMX 2.2/3.0 then an option for inheritance is to allow DSDs to reference HCLs
- HCL isn’t a great name is it’s not a souped-up code list with added features, it actually needs code lists to work, therefore;
- Possible option to change name from HCL to something more useful and correct such as VCL or 
`COLLECTIONOFPOINTERSTOCODESINCODELISTSWITHHIERARCHICALINFORMATIONTHINGY`

**Comment by Tzaphkiel** [comment]
An initial solution using the **codelist inheritance mechanism** was devised with a _set of rules_ forcing the overwritting of parent codes by subsequent children occurences. 
The extension thus constructed would not guaranty compliance with the original codelist. The code that is overwritten may mean something completely different in the new context.

![image](https://user-images.githubusercontent.com/644489/70995419-ce05e280-20d0-11ea-8a9a-96c9ead2bc93.png)

This solution was deemed not complete enough as it did not cover extending codes from _2 or more codelists belonging to different organisation_ which the extender was not neccessarily a part of.

In the last physical TWG meeting (December 2019 - LU), we agreed to investigate a way to reference parent codelists using an **ordered sequence** that the extension would inherit from. The overwriting rules would still apply but this time taking into account multiple parents _in the sequence_ defined in the reference.

![image](https://user-images.githubusercontent.com/644489/70996372-eb3bb080-20d2-11ea-8957-ea77b504d57c.png)

![image](https://user-images.githubusercontent.com/644489/70996419-03abcb00-20d3-11ea-9f55-298f062563bf.png)

We still have to investigate how the **artefact versioning** would affect such inheritance but so far, only complete specific versions would be allowed in the references.

**Comment by stratosn** [comment]
Since SDMX 3.0, a new Codelist can inherit/extend one or more existing Codelists and add, remove or override Codes.
Since a Codelist can inherit multiple Codelists, the order of inheritance is significant and the Codes that come from a "later" ancestor (eg the last in order) override those with identical identifiers. 
In addition, any Codes defined in the new Codelist, override any inherited Codes with identical identifiers.
