### ISSUE TITLE
Support for multi-valued attributes, use case of flags

### ISSUE THREAD

**Issue by tasosc** [sdmx-twg/sdmx-im#5]
(on behalf of Eurostat)
Initial request:
[Domain SDMX request - Multiple flagging.pdf](https://github.com/sdmx-twg/sdmx-ml-v2_1/files/513100/Domain.SDMX.request.-.Multiple.flagging.pdf)

A short summary of the request:
The request is about adding support somehow for data attributes to have more than one code in datasets.

So if we have a Codelist with 3 codes `{r, u, e}`, as an example, it should be possible to have, in a dataset , within an observation attribute (e.g. `OBS_FLAG`) for one specific observation one of the following values:

- `r`
- `{r,u}`
- `{r,e}`
- `{u,e}`
- `{r,u,e}`

See example below, where `OBS_FLAG` attribute uses 2 codes `r`and `u` for a specific observation using space as a separator (` `):

```xml
<generic:Obs>
  <generic:ObsDimension value="2014" />
  <generic:ObsValue value="5.06944075E8" />
  <generic:Attributes>
    <generic:Value id="OBS_FLAG" value="r u" />
  </generic:Attributes>
</generic:Obs>
```

**Comment by Tzaphkiel** [comment]
Rejected, see combined issue with #4 : #6
