### ISSUE TITLE
Support microdata exchange

### ISSUE THREAD

**Issue by Tzaphkiel** [sdmx-twg/sdmx-im#6]
_This issue refers to #4 (Multiple measures) and #5 (Multi-valued attributes)._

### Multiple measures
There have been cases in **SDGs** and **other Statistical Domains** where _multiple measures_ are available for the same indicator. 
Currently SDMX does not support secondary measures. 
The current workaround is to create additional attributes and name them according to a convention.

This would need to be addressed by the TWG to formalise the modeling of multiple measures.

### Multi-valued attributes (flags) aka. Arrays for Attribute values
_(on behalf of Eurostat)_
Initial request:
[Domain SDMX request - Multiple flagging.pdf](https://github.com/sdmx-twg/sdmx-ml-v2_1/files/513100/Domain.SDMX.request.-.Multiple.flagging.pdf)

A short summary of the request:
The request is about adding support somehow for data attributes to have more than one code in datasets.

So if we have a Codelist with 3 codes `{r, u, e}`, as an example, it should be possible to have, in a dataset , within an observation attribute (e.g. `OBS_FLAG`) for one specific observation one of the following values:

- `r`
- `{r,u}`
- `{r,e}`
- `{u,e}`
- `{r,u,e}`

See example below, where `OBS_FLAG` attribute uses 2 codes `r`and `u` for a specific observation using space as a separator (` `):

```xml
<generic:Obs>
  <generic:ObsDimension value="2014" />
  <generic:ObsValue value="5.06944075E8" />
  <generic:Attributes>
    <generic:Value id="OBS_FLAG" value="r u" />
  </generic:Attributes>
</generic:Obs>
```

After le last TWG physical meeting (Dec 2019 - LU), this issue (renamed to "Arrays for Attribute values" to reflect better the use case) is being considered together with sdmx-twg/sdmx-im#4 , since it impacts the dataset message and needs to be combined with the multiple measures issue, for considering also attaching Attributes to Measures.

The proposed idea, at the time of this writing, is to introduce an extension to the current way SDMX Attributes are reported. This means that SDMX Attributes will be reported as now, when a single value is reported; when an array of values needs to be reported for an Attribute, e.g. many status values for Attribute `OBS_STATUS`, then an XML array will be included under the corresponding dataset element that the Attribute is reported, named after the Attribute. For the `OBS_VALUE` example, when reported under the `<Obs>` element:
```xml
<Obs ... >
  <OBS_STATUS>
    <value>D</value>
    <value>B</value>
    <value>Q</value>
  </OBS_STATUS>
```

**Comment by stratosn** [comment]
Multiple Measures, multiple values (array data type) and multilingual uncoded values for Attributes and Measures have been implemented in SDMX 3.0 Information Model.
