### ISSUE TITLE
Use of Regular Expressions to define constraints

### ISSUE THREAD

**Issue by egreising** [sdmx-twg/sdmx-im#8]
Several sets of category items (a variant) can be associated to one classification, but only one is used in a DF or PA, depending of the context. (e.g. ISIC versions in CL_ACTIVITY).
The way this can be achieved is using content constraints attached to the dataflow or provision agreement.
However, the constraint specification must be done “by extension”, thus enumerating all the codes to be included or excluded. The length of this list can be a problem. 
For example, the list of codes to be included in a content constraint to include the items corresponding to the ISIC Rev. 4 variant from the CL_ACTIVITY code list is composed of approximately 770 items.

Using a common prefix to identify all codes belonging to a variant helps in managing long code lists with many variants, like CL_ACTIVITY (e.g. ISIC4_, ISIC3_, NACE2_, AGG_, etc.)
It has been proposed to allow the use of regular expressions in the creation of constraints in order to reduce the length and complexity of their definition.
Nevertheless, to deal with the issue of multiple variants, and considering the adoption of the “prefixed codes” practice, just a “wild card” character would be enough, and make the use of regular expressions  not advisable as it would “overload” the solution
It is suggested to simply use the percentage sign (%) as the wildcard character. 
Following the same example mentioned ut-supra, the more than 770 items can be reduced to a single wildcarded element.

![image](https://user-images.githubusercontent.com/12588753/41564179-51bc54e8-7352-11e8-8d83-a1584c894ef8.png)

**Comment by stratosn** [comment]
This is already supported in SDMX 3.0, as also explained in [`section 6 technical notes`](https://sdmx.org/wp-content/uploads/SDMX_2-1-1-SECTION_6_TechnicalNotes-march-2013.pdf), at **section 10.3.4.2 Combination of Constraints** (lines 1831-1836) and reads:
_A Member Selection may include wildcarding of values (using character ‘%’ to represent zero or more occurrences of any character), as well as cascading through hierarchic structures (e.g., parents in Codelist), or localised values (e.g., text for English only). Lack of locale means any language may match. Cascading values are mutual exclusive to localised values, as the former refer to coded values, while the latter refer to uncoded values._

and more specifically examples:
- **10.3.4.2.7 Use Case 7: A Constraint with wildcards for Codes and removePrefix property** (lines 2117-2126)
- **10.3.4.2.8 Use Case 8: A Constraint with multilingual support on Attributes** (lines 2127-2133)
