### ISSUE TITLE
Identifiable Codelist subsets (sub-domains)

### ISSUE THREAD

**Issue by Tzaphkiel** [sdmx-twg/sdmx-im#9]
The possibility of defining sub-domains (subsets of a Codelist) of a particular domain (Codelist) and being able to refer to it is very appealing and eases modeling in many situations. 

This issue may be related to #2 in the sense that a subset could potentially be used to define a new codelist extension.

The HCL are not to be used for this as what we intend to model is not a hierarchy of any kind but individual groups with no hierarchical relations to each other.

**Comment by stratosn** [comment]
The Codelist extension/composition (as described #2) covers this use case by inheriting a Codelist and removing Codes from it.
This can be achieved by creating a new Codelist and using the `ExclusiveCodeSelection` to exclude all Codes that are going to be removed from the Codelist that is extended, eg in SDMX-ML:
```xml
<str:CodelistExtension>
    <str:Codelist>urn:sdmx:org.sdmx.infomodel.codelist.Codelist=SDMX:CL2(1.0.0)</str:Codelist>
    <str:ExclusiveCodeSelection>
        <str:MemberValue>A</str:MemberValue>
        <str:MemberValue>B</str:MemberValue>
    </str:ExclusiveCodeSelection>
</str:CodelistExtension>
```

The equivalent for Json is `exclusiveCodeSelection`, ie:
```json
"codelistExtensions":[
  {
    "codelist":"urn:sdmx:org.sdmx.infomodel.codelist.Codelist=SDMX:CL2(1.0.0)",
    "exclusiveCodeSelection":{
      "memberValues":[
        "A", "B"
      ]
    }
  }
]
```
